name: IMS Client CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ims-client  # Specify the project directory

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './ims-client/package-lock.json'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Lint
      run: npm run lint
      
    - name: Type check
      run: npm run type-check
      
    - name: Build
      run: npm run build

  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Backend
        uses: actions/checkout@v4
        with:
          repository: Sultan-303/IMS-Backend
          path: backend
          token: ${{ secrets.GH_PAT }}
      
      - name: Start Backend Dev Environment
        run: |
          pwd
          dir
          cd backend
          pwd
          dir
          docker compose -f docker-compose.dev.yml build
          docker compose -f docker-compose.dev.yml up -d

      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./ims-client
          build: npm run build
          start: npm run dev